services:
  # Aplicação Spring Boot
  - type: web
    name: mfc-entrada-atletas
    env: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DATABASE_URL
        fromDatabase:
          name: mfc-postgres
          property: connectionString
      - key: DATABASE_USERNAME
        fromDatabase:
          name: mfc-postgres
          property: user
      - key: DATABASE_PASSWORD
        fromDatabase:
          name: mfc-postgres
          property: password
    healthCheckPath: /api/atletas

databases:
  # Banco de dados PostgreSQL
  - name: mfc-postgres
    databaseName: EntradaAtletas
    user: mfcuser
    plan: free

